In [1]:
import pandas as pd
import numpy as np

In [23]:
#df = pd.read_csv('FFssFF.N.SGL.294K.dat',delim_whitespace=True, names=['z','count'])

In [77]:
data = np.loadtxt('FFssFF.N.SGL.294K.dat')

In [79]:
# select first and second column array
x = data[:,0]
y = data[:,1]

In [94]:
x[i]

129.0

In [97]:
top =[]
bottom = []
mid =int(len(x)/2)

for i in range(mid,0,-1):
    top.append(y[i])
for i in range(mid,int(len(x))):
    bottom.append(y[i])
ans = (np.array(top) + np.array(bottom))/2

xbottom = []
for j in range(mid, int(len(x))):
    xbottom.append(x[j])
zaxis = np.array(xbottom)

In [98]:
zaxis

array([  1.,   3.,   5.,   7.,   9.,  11.,  13.,  15.,  17.,  19.,  21.,
        23.,  25.,  27.,  29.,  31.,  33.,  35.,  37.,  39.,  41.,  43.,
        45.,  47.,  49.,  51.,  53.,  55.,  57.,  59.,  61.,  63.,  65.,
        67.,  69.,  71.,  73.,  75.,  77.,  79.,  81.,  83.,  85.,  87.,
        89.,  91.,  93.,  95.,  97.,  99., 101., 103., 105., 107., 109.,
       111., 113., 115., 117., 119., 121., 123., 125., 127., 129.])

In [85]:
ans

array([3.39 , 3.6  , 3.59 , 3.345, 2.98 , 2.6  , 2.385, 1.97 , 1.58 ,
       1.38 , 1.055, 0.675, 0.43 , 0.285, 0.175, 0.115, 0.075, 0.055,
       0.05 , 0.04 , 0.04 , 0.035, 0.03 , 0.03 , 0.03 , 0.035, 0.04 ,
       0.04 , 0.04 , 0.04 , 0.04 , 0.04 , 0.045, 0.04 , 0.04 , 0.04 ,
       0.04 , 0.035, 0.04 , 0.04 , 0.035, 0.04 , 0.045, 0.05 , 0.05 ,
       0.055, 0.045, 0.045, 0.045, 0.05 , 0.05 , 0.05 , 0.05 , 0.055,
       0.05 , 0.05 , 0.045, 0.045, 0.05 , 0.05 , 0.055, 0.055, 0.06 ,
       0.065, 0.06 ])

In [116]:
file = np.stack((zaxis, ans), axis=1)

In [117]:
file

array([[1.000e+00, 3.390e+00],
       [3.000e+00, 3.600e+00],
       [5.000e+00, 3.590e+00],
       [7.000e+00, 3.345e+00],
       [9.000e+00, 2.980e+00],
       [1.100e+01, 2.600e+00],
       [1.300e+01, 2.385e+00],
       [1.500e+01, 1.970e+00],
       [1.700e+01, 1.580e+00],
       [1.900e+01, 1.380e+00],
       [2.100e+01, 1.055e+00],
       [2.300e+01, 6.750e-01],
       [2.500e+01, 4.300e-01],
       [2.700e+01, 2.850e-01],
       [2.900e+01, 1.750e-01],
       [3.100e+01, 1.150e-01],
       [3.300e+01, 7.500e-02],
       [3.500e+01, 5.500e-02],
       [3.700e+01, 5.000e-02],
       [3.900e+01, 4.000e-02],
       [4.100e+01, 4.000e-02],
       [4.300e+01, 3.500e-02],
       [4.500e+01, 3.000e-02],
       [4.700e+01, 3.000e-02],
       [4.900e+01, 3.000e-02],
       [5.100e+01, 3.500e-02],
       [5.300e+01, 4.000e-02],
       [5.500e+01, 4.000e-02],
       [5.700e+01, 4.000e-02],
       [5.900e+01, 4.000e-02],
       [6.100e+01, 4.000e-02],
       [6.300e+01, 4.000e-02],
       [

In [118]:
np.savetxt('avg_combine.dat',file, delimiter=' ')

In [124]:
df = pd.read_csv('avg_combine.dat', header=None, names=['z','count'], delim_whitespace=True)

In [125]:
df

z  count
0     1.0  3.390
1     3.0  3.600
2     5.0  3.590
3     7.0  3.345
4     9.0  2.980
..    ...    ...
60  121.0  0.055
61  123.0  0.055
62  125.0  0.060
63  127.0  0.065
64  129.0  0.060

[65 rows x 2 columns]

In [120]:
len(df)

65

In [9]:
len(df)

129

In [46]:
data = df['count'].to_numpy()